# INS timeout in seconds before EBS is activated
insTimeout: 8.0
# Time to wait in seconds where we assume the INS failed to initialise
insFailedToInitTimeout: 15.0

# Control timeout in seconds before the EBS is activated
controlTimeout: 1.0
# Time to wait in seconds before we assume the controller failed to initialise
controlFailedToInitTimeout: 25.0